Repository frenck/action-yamllint, pull requests merged in 2021-01, with the labels that each got.

#1 Fix broken links in README
  README.md
Labels: documentation

#2 Fix stale GitHub Action step description
  .github/workflows/stale.yaml
Labels: ci

#3 Documentation tweaks + document alternative
  README.md
Labels: documentation

#4 Add test workflow
  .github/workflows/test.yaml
Labels: ci

#5 Documentation tweaks
  README.md
Labels: documentation

#6 Add additional release tags
  .github/workflows/additional-tags.yaml
  README.md
Labels: ci

#7 Adjust linter workflow with Prettier
  .github/workflows/lint.yaml
  CODE_OF_CONDUCT.md
  README.md
Labels: ci

#8 Fix maintenance vs chore label issue
  .github/labels.yml
  .github/release-drafter.yml
Labels: maintenance

#11 Add /me to example repos
  README.md
Labels: documentation
